# Generated by Django 2.2 on 2019-11-06 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('mailAddless', models.EmailField(max_length=50)),
                ('TEL', models.PositiveIntegerField(max_length=11)),
                ('birthday', models.DateField(max_length=8)),
                ('gender', models.CharField(max_length=3)),
                ('review_star', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='レビュー星')),
                ('reviewComment', models.TextField()),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
