# Generated by Django 2.2 on 2019-11-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='TEL',
        ),
    ]
