# Generated by Django 2.2 on 2020-03-10 09:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashioncategory', models.CharField(max_length=30, verbose_name='ファッションカテゴリ')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name=' 登録日時')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name=' 更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fashionapp', models.CharField(max_length=200, verbose_name='名前')),
                ('story', models.TextField(default='', max_length=1000, verbose_name='ストーリー')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='ファッション 登録日時')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='ファッション 更新日時')),
                ('favorite', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='お気に入り度')),
                ('fashioncategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='age.ClothCategory')),
            ],
        ),
    ]
