# Generated by Django 2.2 on 2020-04-03 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnivImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('mdl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='age.Aniversary')),
            ],
        ),
        migrations.CreateModel(
            name='ClothImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('mdl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='age.Clothes')),
            ],
        ),
        migrations.CreateModel(
            name='ElecImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('mdl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='age.HomeElecApp')),
            ],
        ),
        migrations.CreateModel(
            name='FurnImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('mdl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='age.Furn')),
            ],
        ),
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('mdl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='age.Other')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
