# Generated by Django 2.2 on 2020-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rebviewComment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rebviewStar',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='レビュー星'),
        ),
    ]
