# Generated by Django 2.2 on 2020-01-15 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcategory', models.CharField(max_length=30, verbose_name='食品カテゴリ')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='食品カテゴリ 登録日時')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='食品カテゴリ 更新日時')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=200, verbose_name='食品名')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='食品 登録日時')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='食品 更新日時')),
                ('electID', models.CharField(max_length=50)),
                ('electName', models.CharField(max_length=50)),
                ('electKinds', models.IntegerField(choices=[(1, 'wsh1'), (2, 'vcm1'), (3, 'rck1'), (4, 'ovn1'), (5, 'iln1'), (6, 'sew1'), (7, 'frg1'), (8, 'pot1'), (9, 'acd1'), (10, 'fan1'), (11, 'dry1'), (12, 'lgt1'), (13, 'phn1'), (14, 'hmd1'), (15, 'tvs1'), (16, 'cmr1'), (17, 'smp1'), (18, 'pcn1'), (19, 'ado1'), (20, 'toy1'), (21, 'gme1'), (22, 'oth1')], verbose_name='種類')),
                ('electcreateDate', models.DateTimeField(auto_now_add=True, verbose_name='記念日登録日時')),
                ('electupdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='記念日更新日時')),
                ('annivID', models.CharField(max_length=50)),
                ('annivName', models.CharField(max_length=50)),
                ('annivcreateDate', models.DateTimeField(auto_now_add=True, verbose_name='記念日登録日時')),
                ('annivupdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='記念日更新日時')),
                ('foodcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='age.FoodCategory')),
            ],
        ),
    ]
