# Generated by Django 2.2 on 2020-03-10 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0002_auto_20200309_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniversary',
            name='favorite',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='お気に入り度'),
        ),
        migrations.AddField(
            model_name='food',
            name='favorite',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='お気に入り度'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='favorite',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='お気に入り度'),
        ),
        migrations.AddField(
            model_name='other',
            name='favorite',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='お気に入り度'),
        ),
    ]
