# Generated by Django 2.2 on 2020-03-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0002_clothcategory_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to='images/')),
                ('picture2', models.ImageField(upload_to='images/')),
                ('picture3', models.ImageField(upload_to='images/')),
                ('picture4', models.ImageField(upload_to='images/')),
                ('picture5', models.ImageField(upload_to='images/')),
                ('picture6', models.ImageField(upload_to='images/')),
                ('picture7', models.ImageField(upload_to='images/')),
                ('picture8', models.ImageField(upload_to='images/')),
                ('picture9', models.ImageField(upload_to='images/')),
                ('picture10', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
