# Generated by Django 2.2 on 2020-04-06 11:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0002_auto_20200403_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniversary',
            name='didday',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='記念日が起こった日付'),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='出来事の日付'),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.Aniversary'),
        ),
        migrations.AlterField(
            model_name='anivimage',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.Aniversary'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='出来事の日付'),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.Clothes'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.Clothes'),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='出来事の日付'),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.HomeElecApp'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.HomeElecApp'),
        ),
        migrations.AlterField(
            model_name='furn',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='出来事の日付'),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.Furn'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.Furn'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='other',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 6), verbose_name='出来事の日付'),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.Other'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='mdl',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='age.Other'),
        ),
    ]
