# Generated by Django 2.2 on 2020-01-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0002_auto_20200115_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aniversary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annivID', models.CharField(max_length=50)),
                ('annivName', models.CharField(max_length=50)),
                ('annivcreateDate', models.DateTimeField(auto_now_add=True, verbose_name='記念日登録日時')),
                ('annivupdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='記念日更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='HomeElecAppCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeelecappcegory', models.CharField(max_length=30, verbose_name='家電カテゴリ')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='家電カテゴリ 登録日時')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='家電カテゴリ 更新日時')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='annivID',
        ),
        migrations.RemoveField(
            model_name='food',
            name='annivName',
        ),
        migrations.RemoveField(
            model_name='food',
            name='annivcreateDate',
        ),
        migrations.RemoveField(
            model_name='food',
            name='annivupdateDate',
        ),
        migrations.RemoveField(
            model_name='food',
            name='electID',
        ),
        migrations.RemoveField(
            model_name='food',
            name='electKinds',
        ),
        migrations.RemoveField(
            model_name='food',
            name='electName',
        ),
        migrations.RemoveField(
            model_name='food',
            name='electcreateDate',
        ),
        migrations.RemoveField(
            model_name='food',
            name='electupdateDate',
        ),
        migrations.CreateModel(
            name='HomeElecApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeelecapp', models.CharField(max_length=200, verbose_name='家電')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='家電 登録日時')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='家電 更新日時')),
                ('electcreateDate', models.DateTimeField(auto_now_add=True, verbose_name='記念日登録日時')),
                ('electupdateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='記念日更新日時')),
                ('homeelecategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='age.HomeElecAppCategory')),
            ],
        ),
    ]
