# Generated by Django 2.2 on 2020-03-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0003_auto_20200310_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='favorite',
        ),
    ]
