# Generated by Django 2.2 on 2020-03-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniversary',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='age.Image'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='age.Image'),
        ),
        migrations.AddField(
            model_name='furn',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='age.Image'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='age.Image'),
        ),
        migrations.AddField(
            model_name='other',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='age.Image'),
        ),
    ]
