# Generated by Django 2.2 on 2020-03-15 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0004_auto_20200312_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniversary',
            name='didday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='記念日が起こった日付'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='誕生日（購入日など）'),
        ),
        migrations.AddField(
            model_name='furn',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='誕生日（購入日など）'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='誕生日（購入日など）'),
        ),
        migrations.AddField(
            model_name='other',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='誕生日（購入日など）'),
        ),
    ]
