# Generated by Django 2.2 on 2020-04-11 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0004_auto_20200406_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='noticedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='noticetime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aniversary',
            name='didday',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='記念日が起こった日付'),
        ),
        migrations.AlterField(
            model_name='aniversary',
            name='story',
            field=models.TextField(default='', help_text='そのものへの思い出やエピソードなどを入力してください', max_length=1000, verbose_name='ストーリー'),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='出来事の日付'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='story',
            field=models.TextField(default='', help_text='そのものへの思い出やエピソードなどを入力してください', max_length=1000, verbose_name='ストーリー'),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='出来事の日付'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reviewComment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='出来事の日付'),
        ),
        migrations.AlterField(
            model_name='furn',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='furn',
            name='story',
            field=models.TextField(default='', help_text='そのものへの思い出やエピソードなどを入力してください', max_length=1000, verbose_name='ストーリー'),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='出来事の日付'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='story',
            field=models.TextField(default='', help_text='そのものへの思い出やエピソードなどを入力してください', max_length=1000, verbose_name='ストーリー'),
        ),
        migrations.AlterField(
            model_name='other',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='other',
            name='story',
            field=models.TextField(default='', help_text='そのものへの思い出やエピソードなどを入力してください', max_length=1000, verbose_name='ストーリー'),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 11), verbose_name='出来事の日付'),
        ),
    ]
