# Generated by Django 2.2 on 2020-03-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0004_remove_food_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniversary',
            name='annivapp',
            field=models.CharField(max_length=200, verbose_name='記念日名'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='HomeElecApp',
            field=models.CharField(max_length=200, verbose_name='家電名'),
        ),
        migrations.AlterField(
            model_name='other',
            name='otherapp',
            field=models.CharField(max_length=200, verbose_name='名前'),
        ),
    ]
