# Generated by Django 2.2 on 2020-03-17 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0005_auto_20200315_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furn',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 17), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture1',
            field=models.ImageField(upload_to='images/', verbose_name='写真'),
        ),
    ]
