# Generated by Django 2.2 on 2020-03-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0005_auto_20200310_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('furnname', models.CharField(max_length=200, verbose_name='家具名')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='家具 登録日時')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='家具 更新日時')),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
    ]
