# Generated by Django 2.2 on 2020-03-17 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0006_auto_20200317_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniversary',
            name='didday',
            field=models.DateField(default=datetime.date(2020, 3, 17), verbose_name='記念日が起こった日付'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 17), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 17), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='other',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 17), verbose_name='誕生日（購入日など）'),
        ),
    ]
