# Generated by Django 2.2 on 2020-03-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0007_auto_20200317_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='fashioncategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='age.ClothCategory', verbose_name='ファッションの種類'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='ElecCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='age.HomeElecAppCategory', verbose_name='家電の種類'),
        ),
        migrations.AlterField(
            model_name='other',
            name='othercategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='age.OtherCategory', verbose_name='種類'),
        ),
    ]
