# Generated by Django 2.2 on 2020-03-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0008_auto_20200317_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rebviewComment',
            new_name='reviewComment',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='rebviewStar',
            new_name='reviewStar',
        ),
        migrations.AlterField(
            model_name='furn',
            name='img',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='age.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture1',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture10',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture5',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture6',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture7',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture8',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture9',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
