# Generated by Django 2.2 on 2020-03-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0010_auto_20200317_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furn',
            name='img',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='age.Image'),
        ),
    ]
