# Generated by Django 2.2 on 2020-03-18 01:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0011_auto_20200317_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(null=True, upload_to='images/', verbose_name='写真')),
                ('picture2', models.ImageField(null=True, upload_to='images/')),
                ('picture3', models.ImageField(null=True, upload_to='images/')),
                ('picture4', models.ImageField(null=True, upload_to='images/')),
                ('picture5', models.ImageField(null=True, upload_to='images/')),
                ('picture6', models.ImageField(null=True, upload_to='images/')),
                ('picture7', models.ImageField(null=True, upload_to='images/')),
                ('picture8', models.ImageField(null=True, upload_to='images/')),
                ('picture9', models.ImageField(null=True, upload_to='images/')),
                ('picture10', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElecImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(null=True, upload_to='images/', verbose_name='写真')),
                ('picture2', models.ImageField(null=True, upload_to='images/')),
                ('picture3', models.ImageField(null=True, upload_to='images/')),
                ('picture4', models.ImageField(null=True, upload_to='images/')),
                ('picture5', models.ImageField(null=True, upload_to='images/')),
                ('picture6', models.ImageField(null=True, upload_to='images/')),
                ('picture7', models.ImageField(null=True, upload_to='images/')),
                ('picture8', models.ImageField(null=True, upload_to='images/')),
                ('picture9', models.ImageField(null=True, upload_to='images/')),
                ('picture10', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FurnImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(null=True, upload_to='images/', verbose_name='写真')),
                ('picture2', models.ImageField(null=True, upload_to='images/')),
                ('picture3', models.ImageField(null=True, upload_to='images/')),
                ('picture4', models.ImageField(null=True, upload_to='images/')),
                ('picture5', models.ImageField(null=True, upload_to='images/')),
                ('picture6', models.ImageField(null=True, upload_to='images/')),
                ('picture7', models.ImageField(null=True, upload_to='images/')),
                ('picture8', models.ImageField(null=True, upload_to='images/')),
                ('picture9', models.ImageField(null=True, upload_to='images/')),
                ('picture10', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(null=True, upload_to='images/', verbose_name='写真')),
                ('picture2', models.ImageField(null=True, upload_to='images/')),
                ('picture3', models.ImageField(null=True, upload_to='images/')),
                ('picture4', models.ImageField(null=True, upload_to='images/')),
                ('picture5', models.ImageField(null=True, upload_to='images/')),
                ('picture6', models.ImageField(null=True, upload_to='images/')),
                ('picture7', models.ImageField(null=True, upload_to='images/')),
                ('picture8', models.ImageField(null=True, upload_to='images/')),
                ('picture9', models.ImageField(null=True, upload_to='images/')),
                ('picture10', models.ImageField(null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='AnnivImage',
        ),
        migrations.AlterField(
            model_name='aniversary',
            name='didday',
            field=models.DateField(default=datetime.date(2020, 3, 18), verbose_name='記念日が起こった日付'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 18), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='age.ClothImage'),
        ),
        migrations.AlterField(
            model_name='furn',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 18), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='furn',
            name='img',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='age.FurnImage'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 18), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='age.ElecImage'),
        ),
        migrations.AlterField(
            model_name='other',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 18), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='other',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='age.OtherImage'),
        ),
    ]
