# Generated by Django 2.2 on 2020-03-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0012_auto_20200318_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annivimage',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='annivimage',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='annivimage',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='annivimage',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='annivimage',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='annivimage',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='annivimage',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='annivimage',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='annivimage',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='annivimage',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='clothimage',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='elecimage',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='furnimage',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
