# Generated by Django 2.2 on 2020-03-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0014_auto_20200319_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherimage',
            name='title',
        ),
    ]
