# Generated by Django 2.2 on 2020-03-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0015_remove_otherimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elecimage',
            name='title',
        ),
    ]
