# Generated by Django 2.2 on 2020-03-20 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0016_remove_elecimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aniversary',
            name='img',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='img',
        ),
        migrations.RemoveField(
            model_name='furn',
            name='img',
        ),
        migrations.RemoveField(
            model_name='homeelecapp',
            name='img',
        ),
        migrations.RemoveField(
            model_name='other',
            name='img',
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='aniversary',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='furn',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='homeelecapp',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture10',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture6',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture7',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture8',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='other',
            name='picture9',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aniversary',
            name='didday',
            field=models.DateField(default=datetime.date(2020, 3, 20), verbose_name='記念日が起こった日付'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 20), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='furn',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 20), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 20), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='other',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 20), verbose_name='誕生日（購入日など）'),
        ),
        migrations.DeleteModel(
            name='AnnivImage',
        ),
        migrations.DeleteModel(
            name='ClothImage',
        ),
        migrations.DeleteModel(
            name='ElecImage',
        ),
        migrations.DeleteModel(
            name='FurnImage',
        ),
        migrations.DeleteModel(
            name='OtherImage',
        ),
    ]
