# Generated by Django 2.2 on 2020-03-27 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0017_auto_20200320_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='fashioncategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='fashionapp',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='furn',
            old_name='furnname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='homeelecapp',
            old_name='ElecCategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='homeelecapp',
            old_name='HomeElecApp',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='othercategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='other',
            old_name='otherapp',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='aniversary',
            name='didday',
            field=models.DateField(default=datetime.date(2020, 3, 27), verbose_name='記念日が起こった日付'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 27), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='furn',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 27), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 27), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='other',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 3, 27), verbose_name='誕生日（購入日など）'),
        ),
    ]
