# Generated by Django 2.2 on 2020-04-01 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0021_auto_20200328_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture6', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture7', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture8', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture9', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('picture10', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='aniversary',
            name='didday',
            field=models.DateField(default=datetime.date(2020, 4, 1), verbose_name='記念日が起こった日付'),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 1), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furn',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 1), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 1), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='other',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 1), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 1)),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history1', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('history2', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('history3', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('history4', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('history5', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('history6', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('history7', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('history8', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('history9', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('history10', models.TextField(blank=True, default='', max_length=100, null=True)),
                ('historyday1', models.DateField(default=datetime.date(2020, 4, 1))),
                ('historyday2', models.DateField(default=datetime.date(2020, 4, 1))),
                ('historyday3', models.DateField(default=datetime.date(2020, 4, 1))),
                ('historyday4', models.DateField(default=datetime.date(2020, 4, 1))),
                ('historyday5', models.DateField(default=datetime.date(2020, 4, 1))),
                ('historyday6', models.DateField(default=datetime.date(2020, 4, 1))),
                ('historyday7', models.DateField(default=datetime.date(2020, 4, 1))),
                ('historyday8', models.DateField(default=datetime.date(2020, 4, 1))),
                ('historyday9', models.DateField(default=datetime.date(2020, 4, 1))),
                ('historyday10', models.DateField(default=datetime.date(2020, 4, 1))),
                ('mdl', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='age.HomeElecApp')),
            ],
        ),
    ]
