# Generated by Django 2.2 on 2020-04-02 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0022_auto_20200401_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='history10',
        ),
        migrations.RemoveField(
            model_name='history',
            name='history2',
        ),
        migrations.RemoveField(
            model_name='history',
            name='history3',
        ),
        migrations.RemoveField(
            model_name='history',
            name='history4',
        ),
        migrations.RemoveField(
            model_name='history',
            name='history5',
        ),
        migrations.RemoveField(
            model_name='history',
            name='history6',
        ),
        migrations.RemoveField(
            model_name='history',
            name='history7',
        ),
        migrations.RemoveField(
            model_name='history',
            name='history8',
        ),
        migrations.RemoveField(
            model_name='history',
            name='history9',
        ),
        migrations.RemoveField(
            model_name='history',
            name='historyday10',
        ),
        migrations.RemoveField(
            model_name='history',
            name='historyday2',
        ),
        migrations.RemoveField(
            model_name='history',
            name='historyday3',
        ),
        migrations.RemoveField(
            model_name='history',
            name='historyday4',
        ),
        migrations.RemoveField(
            model_name='history',
            name='historyday5',
        ),
        migrations.RemoveField(
            model_name='history',
            name='historyday6',
        ),
        migrations.RemoveField(
            model_name='history',
            name='historyday7',
        ),
        migrations.RemoveField(
            model_name='history',
            name='historyday8',
        ),
        migrations.RemoveField(
            model_name='history',
            name='historyday9',
        ),
        migrations.AlterField(
            model_name='aniversary',
            name='didday',
            field=models.DateField(default=datetime.date(2020, 4, 2), verbose_name='記念日が起こった日付'),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='anivhistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 2), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='clothhistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='elechistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furn',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 2), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='furnhistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='history',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='homeelecapp',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 2), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='other',
            name='birthday',
            field=models.DateField(default=datetime.date(2020, 4, 2), verbose_name='誕生日（購入日など）'),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday1',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AlterField(
            model_name='otherhistory',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
    ]
