# Generated by Django 2.2 on 2020-04-02 12:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age', '0023_auto_20200402_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='history10',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history2',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history3',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history4',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history5',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history6',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history7',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history8',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='history9',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='historyday10',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AddField(
            model_name='history',
            name='historyday2',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AddField(
            model_name='history',
            name='historyday3',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AddField(
            model_name='history',
            name='historyday4',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AddField(
            model_name='history',
            name='historyday5',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AddField(
            model_name='history',
            name='historyday6',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AddField(
            model_name='history',
            name='historyday7',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AddField(
            model_name='history',
            name='historyday8',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
        migrations.AddField(
            model_name='history',
            name='historyday9',
            field=models.DateField(default=datetime.date(2020, 4, 2)),
        ),
    ]
