# Generated by Django 2.2 on 2019-11-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=200)),
                ('mailAddress', models.EmailField(max_length=200)),
                ('passWord', models.CharField(max_length=128)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(0, '男性'), (1, '女性'), (2, '不明')], default=2, verbose_name='性別')),
                ('rebviewStar', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='レビュー星')),
                ('rebviewComment', models.TextField()),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='ユーザー登録日時')),
                ('updateDate', models.DateTimeField(auto_now=True, null=True, verbose_name='ユーザー情報更新日時')),
            ],
        ),
    ]
